---
title: "Obesity amongst men, NFHS - 5"
author: "Arkaprabha Gun, Tushar Garg"
date: "`r Sys.Date()`"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo=F,message=F, warning=F)
suppressMessages(if (!require("pacman")) install.packages("pacman"))
pacman::p_load(tidyverse,lubridate,rio,janitor,here,gtsummary,survey,haven,labelled,sjlabelled,performance,jtools)
```

```{r import, include=F}
# importing individual recode (MR)
import_men <- haven::read_dta(here("Data_raw","IAMR7EDT","IAMR7EFL.DTA"), 
                              col_select = c(mv001,mv002,mv003, mv005, mv024, smdist, mv012, mv025, mv106, mv130, sm118, mv190, sm630g, smb305,mv021,mv023))

# importing household recode (PR)
import_men_household <- haven::read_dta(here("Data_raw","IAPR7EDT","IAPR7EFL.DTA"), 
                                        col_select = c(hv001, hv002, hvidx, hb40, hb2, hb3))

# rename variables in PR
import_men_household <- import_men_household %>%
  mutate(mv001=hv001) %>%
  mutate(mv002=hv002) %>%
  mutate(mv003=hvidx) 

# pulling data from PR into MR
import_men <- merge(import_men,import_men_household,by=c("mv001", "mv002", "mv003"))

rm(import_men_household)

dict_import_men <- labelled::generate_dictionary(import_men)

# excluding men less than 18 years of age and missing values
men <- import_men %>% 
  # excluding  men less than 18 years
  filter(mv012 >= 18) %>% 
  # height and weight - recoding refusal, not present, other to NA
  mutate(across(c(hb2, hb3), ~replace(., . %in% c(9994,9995,9996), NA))) %>% 
  # BMI - 9998 flagged cases to NA
  mutate(hb40 = na_if(hb40, 9998)) %>% 
  # waist circumference - 999.5 and 999.6 to NA
  mutate(s305 = replace(smb305, smb305 %in% c(999.5,999.6), NA)) %>% 
  
   # filtering NA in waist circumference
  filter(!is.na(s305)) %>% 
  
  # filtering where (height and weight) or BMI is not available
  filter(!((is.na(hb2)|is.na(hb3))&is.na(hb40))) %>% 
  # salvaging missing BMI using height and weight to calculate BMI
  mutate(hb40 = if_else(is.na(hb40),(hb2/(hb3/100)^2),hb40)) %>% 
  # invalid BMI values to NA per the DHS manual (hb40<1200 | hb40>6000)
  mutate(hb40 = if_else(hb40 < 1200 | hb40 > 6000, NA_real_, hb40)) %>% 
  # filtering NA in BMI
  filter(!is.na(hb40)) %>% 
  
  # height & weight has one decimal and BMI has two in the dataset
  mutate(across(c(hb2, hb3), ~./10),
         hb40 = hb40/100) %>%
  
  # renaming and setting variable labels
  rename(men_sample_weight = mv005,
         age = mv012,
         state = mv024,
         residence = mv025,
         education = mv106,
         religion = mv130,
         wealth = mv190,
         weight_kg = hb2,
         height_cm = hb3,
         bmi = hb40,
         district = smdist,
         caste = sm118,
         meat = sm630g,
         waist_cm = smb305) %>%
  
  # creating age categories
  mutate(age_category = cut(age, 
                            breaks = c(17, 29, 39, 49, 54), 
                            labels = c("18-29", "30-39", "40-49", "50-54"))) %>% 
  # defining obesity as per waist circumference and BMI criteria 
  # men: WC ≥90 cm, BMI ≥25 (ref: The Asia-Pacific perspective : redefining obesity and its treatment,2000)
  mutate(obese_wtcircum = factor(if_else((waist_cm >= 90), "Obese", "Non-obese"),
                                 levels = c("Obese","Non-obese")),
         obese_bmi = factor(if_else((bmi >= 25), "Obese", "Non-obese"),
                            levels = c("Obese","Non-obese"))) %>% 
  
  dplyr::select(-c(height_cm,weight_kg,waist_cm))


dict_men <- labelled::generate_dictionary(men)

# haven and sjlabelled labelling function
men_original <- men

men <- men_original %>% 
  mutate(across(where(haven::is.labelled), haven::as_factor)) %>%
  # sjlabelled::label_to_colnames() %>%
  # haven::zap_label() %>%
  haven::zap_formats() 

# capitalizing values of factor variables
men <- men %>%
  mutate(across(where(is.factor), ~factor(str_to_sentence(as.character(.))))) %>% 
  mutate(meat = fct_relevel(meat, c("Never","Occasionally","Weekly","Daily")),
         residence = fct_relevel(residence, c("Rural","Urban")),
         education = fct_relevel(education, c("No education","Primary","Secondary","Higher")),
         wealth = fct_relevel(wealth, c("Poorest","Poorer","Middle","Richer","Richest"))
  ) %>% 
  mutate(religion = fct_relevel(fct_recode(religion, "Buddhist" = "Buddhist / neo-buddhist", "Other" = "Parsi / zoroastrian", "Other" = "Jewish", "Other" = "No religion"), 
                                c("Hindu", "Muslim", "Christian", "Sikh","Buddhist","Jain","Other")),
         
         caste = fct_relevel(fct_recode(caste, "Other backward class" = "Obc"), 
                             c("Schedule caste","Schedule tribe","Other backward class","Don't know","None of them" )),
  ) %>% 
  
  labelled::set_variable_labels(men_sample_weight = "men's Sample Weight",
                                age = "Age in years",
                                age_category = "Age category",
                                state = "State",
                                residence = "Type of Residence",
                                education = "Highest Education Level",
                                religion = "Religion",
                                wealth = "Wealth Index",
                                bmi = "Body Mass Index",
                                district = "District",
                                caste = "Caste",
                                meat = "Frequency of Eating Meat",
                                obese_wtcircum = "Obesity WC",
                                obese_bmi = "Obesity BMI") 

# creating a new unique district variable
men <- men %>%
  unite(district_id, state, district, sep = "_",remove = FALSE)

# creating a reference table for state and district variables
district_details <- men %>%
  distinct(district_id, state, district)
```

```{r flowchart}
temp <- import_men

# Create a list of transformation functions
transformations <- list(
  "Step 1 - Excluding men less than 18 years" = 
    function(data) {filter(data, mv012 >= 18)},
  
  "Step 2 - Height and weight recoding" = 
    function(data) {mutate(data, across(c(hb2, hb3), ~replace(., . %in% c(9994, 9995, 9996), NA)))},
  
  "Step 3 - BMI recoding" = 
    function(data) {mutate(data, hb40 = na_if(hb40, 9998))},
  
  "Step 4 - Waist circumference recoding" = 
    function(data) {mutate(data, s305 = replace(smb305, smb305 %in% c(999.5, 999.6), NA))},
  
  "Step 5 - Filtering NA in waist circumference" = 
    function(data) {filter(data, !is.na(s305))},
  
  "Step 6 - Filtering where (height and weight) or BMI is not available" = 
    function(data) {filter(data, !((is.na(hb2)|is.na(hb3))&is.na(hb40)))},
  
  "Step 7 - Salvaging missing BMI using height and weight" = 
    function(data) {mutate(data, hb40 = if_else(is.na(hb40), round(hb2 / (hb3 / 100) ^ 2, 2), hb40))},
  
  "Step 8 - Invalid BMI values to NA per the DHS manual" = 
    function(data) {mutate(data, hb40 = if_else(hb40 < 1200 | hb40 > 6000, NA, hb40))},
  
  "Step 9 - Filtering NA in BMI" = 
    function(data) {filter(data, !is.na(hb40))}
)

# Initialize a tibble to store row count after each step
row_counts <- tibble(Step = character(), Rows = integer()) %>% 
  # Add a row with the initial number of rows in 'men'
  add_row(., Step = "Initial number of rows", Rows = nrow(temp))

# Apply each transformation and save the row count
for (i in names(transformations)) {
  temp <- transformations[[i]](temp)
  row_counts <- add_row(row_counts, Step = i, Rows = nrow(temp))
}

# Add a column with the difference in row count between steps
men_row_counts <- row_counts %>%
  mutate(Difference = Rows - lag(Rows, default = first(Rows)))

rm(list = c("temp", "i", "transformations","row_counts"))

# The Difference column in the men_row_counts dataframe indicates the change in the number of rows after each transformation step, showing how many rows were removed compared to the previous step.
```

```{r ease of setup+testing}
# The advantage of this approach is that it significantly reduces computation time when setting up and testing the code.
# As a result, the 'men' dataset is now a smaller, more manageable dataset
# set.seed(226)
# men <- men %>% sample_frac(0.01)
```

```{r survey design}
# Calculate Weight:
men$wt <- men$men_sample_weight / 1000000

#Specifying Complex Survey Design (with 2-stage sampling)
NFHS5_design <- svydesign(id = men$mv021, strata = men$mv023, weights = men$wt, data = men, nest = TRUE)
options(survey.lonely.psu = "adjust")
```

```{r descriptive summary}
# theme_gtsummary_journal("lancet")

men_prev <- tbl_svysummary(NFHS5_design, 
                         include = c(obese_wtcircum,obese_bmi),
                         digits = list(all_categorical() ~ c(0,1))) %>% 
  add_ci(style_fun = everything() ~ purrr::partial(style_number, scale = 100, digits = 1))

men_prev_wc <- tbl_svysummary(NFHS5_design, by = obese_wtcircum, 
                              include = c(age_category,residence,education,religion,wealth,caste,meat),
                              statistic = list(all_categorical() ~ "{p}% ({n})"),
                              missing_text = "NA",
                              percent = "row") %>% 
  add_ci(pattern = "{stat} [{ci}]",
         #for religion, try "svyprop.logit" when using full data
         method = religion ~ "svyprop.beta") %>% 
  add_overall(last = TRUE,
              statistic = ~"{n}")

men_prev_bmi <- tbl_svysummary(NFHS5_design, by = obese_bmi, 
                               include = c(age_category,residence,education,religion,wealth,caste,meat),
                               statistic = list(all_categorical() ~ "{p}% ({n})"),
                               missing_text = "NA",
                               percent = "row") %>% 
  add_ci(pattern = "{stat} [{ci}]",
         #for religion, try "svyprop.logit" when using full data
         method = religion ~ "svyprop.beta") %>% 
  add_overall(last = TRUE,
              statistic = ~"{n}")

men_prev
men_prev_wc
men_prev_bmi
```

```{r fitting model}
men_model_uv_wc <- men %>%
  select(obese_wtcircum,age_category,residence,education,religion,wealth,caste,meat) %>%
  tbl_uvregression(method = svyglm,
                   y = obese_wtcircum,
                   method.args = list(design=NFHS5_design, family = quasibinomial()),
                   exponentiate = TRUE,
                   pvalue_fun = ~ style_pvalue(.x, digits = 2))

men_model_adj_wc <- svyglm(obese_wtcircum ~ age_category+residence+education+religion+wealth+caste+meat, 
                           design=NFHS5_design, data = men, family = quasibinomial())

# men_model_adj_wc %>% 
#   model_performance()
# 
# summ(men_model_adj_wc, vifs = T)

men_model_adj_wc_est <- men_model_adj_wc %>% 
  tbl_regression(exponentiate = T)

men_model_uv_wc
men_model_adj_wc_est
```

```{r prevalence by state-district}
# obesity prevalence disaggregated by state
men_state_wc <- tbl_svysummary(NFHS5_design, by = obese_wtcircum, 
                               include = c(state),
                               statistic = list(all_categorical() ~ "{p}% ({n})"),
                               missing_text = "NA",
                               percent = "row") %>% 
  add_ci(pattern = "{stat} [{ci}]") %>% 
  add_overall(last = TRUE,
              statistic = ~"{n}")

men_state_wc

state_est <- svyby(~obese_wtcircum, ~state, NFHS5_design, svymean, keep.names = FALSE, na.rm = TRUE, vartype = c("se", "ci"), multicore = TRUE) %>%
  select(!contains("Non-")) %>% 
  rename(prev_obese = obese_wtcircumObese,
         se_obese = se.obese_wtcircumObese,
         ci_l_obese = ci_l.obese_wtcircumObese,
         ci_u_obese = ci_u.obese_wtcircumObese) %>%
  mutate(across(where(is.numeric), ~ round(.x * 100, 1)))

state_count <- svyby(~obese_wtcircum, ~state, NFHS5_design, svytotal, keep.names = FALSE, na.rm = TRUE, multicore = TRUE) %>% 
  select(!starts_with("se.")) %>% 
  mutate(n = round(rowSums(select(., `obese_wtcircumNon-obese`,`obese_wtcircumObese`), na.rm = TRUE),0)) %>% 
  select(state,n)

men_state_wc_df <- merge(state_est, state_count, by = "state")

# obesity prevalence disaggregated by district
men_district_wc <- tbl_svysummary(NFHS5_design, by = obese_wtcircum, 
                                  include = c(district_id),
                                  statistic = list(all_categorical() ~ "{p}% ({n})"),
                                  missing_text = "NA",
                                  percent = "row") %>% 
  add_ci(pattern = "{stat} [{ci}]") %>% 
  add_overall(last = TRUE,
              statistic = ~"{n}")

district_est <- svyby(~obese_wtcircum, ~district_id, NFHS5_design, svymean, keep.names = FALSE, na.rm = TRUE, vartype = c("se", "ci"), multicore = TRUE) %>%
  select(!contains("Non-")) %>% 
  rename(prev_obese = obese_wtcircumObese,
         se_obese = se.obese_wtcircumObese,
         ci_l_obese = ci_l.obese_wtcircumObese,
         ci_u_obese = ci_u.obese_wtcircumObese) %>%
  mutate(across(where(is.numeric), ~ round(.x * 100, 1)))

district_count <- svyby(~obese_wtcircum, ~district_id, NFHS5_design, svytotal, keep.names = FALSE, na.rm = TRUE,multicore = TRUE) %>% 
  select(!starts_with("se.")) %>% 
  mutate(n = round(rowSums(select(., `obese_wtcircumNon-obese`,`obese_wtcircumObese`), na.rm = TRUE),0)) %>% 
  select(district_id,n)

district <- merge(district_est, district_count, by = "district_id")

men_district_wc <- merge(district,district_details, by = "district_id") %>% 
  mutate(state = str_to_title(state),
         district = str_to_title(district))
```

```{r butchering gtsummary objects}
# gtsummary::tbl_buther will reduce the size of tbl_x objects
# Identify tbl_x objects
objs_to_butcher <- ls()[sapply(ls(), function(obj_name) {
  obj <- get(obj_name)
  any(c("tbl_regression", "tbl_uvregression", "tbl_svysummary") %in% class(obj))
})]

# Apply tbl_butcher to those objects and assign back to the same name
for(obj_name in objs_to_butcher) {
  assign(obj_name, tbl_butcher(get(obj_name)))
}
```

```{r export}
export(men_district_wc,here("Output","men_dist_obesity_prev_wc.xlsx"))

# save all objects with men_ prefix except "men_original"and "men_model_adj_wc"
save(list = setdiff(ls(pattern = "^men_"), c("men_original","men_model_adj_wc")), file = here("Output", "men_output.Rdata"))

# save all objects with men_ prefix
# save(list = ls(pattern = "^men_"), file = here("Output","men_output.Rdata"))
```

```{r export for visualization}
# Get the list of objects based on your criteria
viz_objects <- setdiff(ls(pattern = "^men_"), c("men_original", "men_model_adj_wc"))

# Apply as_data_frame() to these objects and overwrite them
for (obj_name in viz_objects) {
  assign(obj_name, as_data_frame(get(obj_name)))
}

save(list = setdiff(ls(pattern = "^men_"), c("men_original","men_model_adj_wc")), file = here("Output", "men_output_viz.Rdata"))
```

```{r session info}
sessioninfo::session_info(pkgs = c("loaded", "attached")[1], to_file = here("Session info","session_info_men.txt"))
```