---
title: "Exploratory Data Analysis"
author: "Arkaprabha Gun, Tushar Garg"
date: "`r Sys.Date()`"
---

```{r}
library(pacman)
pacman::p_load(tidyselect, here, ISOcodes, survey, expss, tidyverse,
       haven, dplyr, ggplot2, labelled, rmarkdown, readxl, naniar,
       ggiraph, xlsx, stringdist, foreign, here, janitor)
pacman::p_load(tidyverse, lubridate, rio, janitor, here, gtsummary,writexl,openxlsx,DataExplorer)
```




```{r}
# ### UNCOMMENT AND RUN FOLLOWING CODE FIRST TIME running the code
# 
# NFHS_IR <- read.dta("Data/IAIR7EFL.DTA",convert.factors = TRUE)
# save(NFHS_IR,file = "Data/NFHS_IR.RData")
# Load Data:
load("~/NFHS_AbdominalObesity/Data/NFHS_IR.RData")
NFHS_IR <- x
```

#Using the 5 % Subsample


```{r}
# Set the seed for replicability
set.seed(123)

# Sample 5% of the dataframe
sampled_df <- NFHS_IR %>% filter(!is.na(s305))%>% sample_frac(0.05)

# Print the sampled dataframe
print(sampled_df)
```


```{r}


# Calculate Weight:
sampled_df$wt <- sampled_df$v005/ 1000000


#plots histogram by waist circumference 

plot_histogram(sampled_df$s305) ## Significant portion of outliers > 900 cm waist circumference

```

```{r}
library(naniar)

plot_missing(data.frame(s305 = sampled_df$s305))
```



```{r}
sampled_df <- sampled_df %>%
  mutate(wtcircum_obese = if_else((s305> 80), 1, 0))

```



```{r}
#Specifying Complex Survey Design (with 2-stage sampling)
NFHS5_design <- svydesign(id = sampled_df$v021, strata = sampled_df$v023, weights = sampled_df$wt, data = sampled_df, nest = TRUE)
options(survey.lonely.psu = "adjust")


```

```{r}
histogram_data <- svyhist(~ s305, design = NFHS5_design)

```

```{r}
#Abdominal Obesity by Gender
prop_abcircum_obese <- svyby(~wtcircum_obese, ~v024, NFHS5_design, svymean, prop = "weights",na.rm = TRUE,multicore = TRUE,vartype = c("se", "ci"))

```

```{r}
#Percentage Prevalence by Gender
perc_abcircum_obese <- prop_abcircum_obese %>% mutate_all(~.* 100)
```
```{r}
perc_abcircum_obese
```

```{r}
pacman::p_load(ggplot2, sf, rnaturalearth, rnaturalearthdata,devtools)

```


```{r}
library(stringdist)
library(ISOcodes)
# Import ISO 3166-2 codes
ISO_3166_2
ISO_3166_2_IN<- subset(ISO_3166_2, grepl("^IN", Code))

perc_abcircum_obese$v024<- rownames(perc_abcircum_obese)



# Fuzzy match state names to ISO 3166-2 codes
perc_abcircum_obese$iso <- sapply(perc_abcircum_obese$v024, function(State) {
  # Calculate the string distances between the state name and all ISO 3166-2 codes
  dists <- stringdist(State, ISO_3166_2_IN$Name)
  
  # Find the index of the closest matching ISO 3166-2 code
  index <- which.min(dists)
  
  # Extract the corresponding ISO 3166-2 code
  iso_code <- ISO_3166_2_IN$Code[index]
  
  # Return the ISO 3166-2 code
  iso_code
})

```
```{r}
pacman::p_load(ggplot2, sf, rnaturalearth, rnaturalearthdata,leaflet,webshot,htmlwidgets,htmltools)

india_shape <- ne_states(country = "India", returnclass = "sf")
joined_data <- left_join(india_shape, perc_abcircum_obese, by = c("iso_3166_2" = "iso"))


```
```{r}
# Create a color palette based on the values of wtcircum_obese
color_pal <- colorNumeric(
  palette = "RdYlBu",
  domain = joined_data$wtcircum_obese,reverse = TRUE
)

title_html <- tags$h3("Prevalence of Abdominal Obesity among women, across Indian States (NFHS-5)")

# Create the chloropleth map with the updated color scale
leaflet_map<-leaflet(joined_data) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(
    fillColor = ~color_pal(wtcircum_obese),
    weight = 1,
    color = "black",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 2,
      color = "white",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~paste0(
      name,
      ": ",
      format(wtcircum_obese, nsmall = 1),
      "%"
    ),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  )%>%
  # Add a legend
  addLegend(
    position = "bottomright",
    pal = color_pal,
    values = ~wtcircum_obese,
    title = "Obesity Rate",
    opacity = 1
  ) %>%
  # Add a custom control for the map title
   addControl(
    html = title_html,
    position = "topright"
  )

leaflet_map

```


```{r}
saveWidget(leaflet_map, file = "chloropleth_map.html")

```

```{r}
# Set the seed for replicability
set.seed(123)

# Sample 5% of the dataframe
NFHS_IR <- NFHS_IR %>% filter(!is.na(s305))%>% sample_frac(0.05)

# Print the sampled dataframe
print(NFHS_IR)
```


```{r}


# Calculate Weight:
NFHS_IR$wt <- NFHS_IR$v005/ 1000000


#plots histogram by waist circumference 

plot_histogram(NFHS_IR$s305) ## Significant portion of outliers > 900 cm waist circumference

```

```{r}
library(naniar)

plot_missing(data.frame(s305 = NFHS_IR$s305))
```



```{r}
NFHS_IR <- NFHS_IR %>%
  mutate(wtcircum_obese = if_else((s305> 80), 1, 0))

```



```{r}
#Specifying Complex Survey Design (with 2-stage sampling)
NFHS5_design <- svydesign(id = NFHS_IR$v021, strata = NFHS_IR$v023, weights = NFHS_IR$wt, data = NFHS_IR, nest = TRUE)
options(survey.lonely.psu = "adjust")


```

```{r}
histogram_data <- svyhist(~ s305, design = NFHS5_design)

```

```{r}
#Abdominal Obesity by Gender
prop_abcircum_obese <- svyby(~wtcircum_obese, ~v024, NFHS5_design, svymean, prop = "weights",na.rm = TRUE,multicore = TRUE,vartype = c("se", "ci"))

```

```{r}
#Percentage Prevalence by Gender
perc_abcircum_obese <- prop_abcircum_obese %>% mutate_all(~.* 100)
```
```{r}
perc_abcircum_obese
```

```{r}
pacman::p_load(ggplot2, sf, rnaturalearth, rnaturalearthdata,devtools)

```


```{r}
library(stringdist)
library(ISOcodes)
# Import ISO 3166-2 codes
ISO_3166_2
ISO_3166_2_IN<- subset(ISO_3166_2, grepl("^IN", Code))

perc_abcircum_obese$v024<- rownames(perc_abcircum_obese)



# Fuzzy match state names to ISO 3166-2 codes
perc_abcircum_obese$iso <- sapply(perc_abcircum_obese$v024, function(State) {
  # Calculate the string distances between the state name and all ISO 3166-2 codes
  dists <- stringdist(State, ISO_3166_2_IN$Name)
  
  # Find the index of the closest matching ISO 3166-2 code
  index <- which.min(dists)
  
  # Extract the corresponding ISO 3166-2 code
  iso_code <- ISO_3166_2_IN$Code[index]
  
  # Return the ISO 3166-2 code
  iso_code
})

```
```{r}
pacman::p_load(ggplot2, sf, rnaturalearth, rnaturalearthdata,leaflet,webshot,htmlwidgets,htmltools)

india_shape <- ne_states(country = "India", returnclass = "sf")
joined_data <- left_join(india_shape, perc_abcircum_obese, by = c("iso_3166_2" = "iso"))


```
```{r}
# Create a color palette based on the values of wtcircum_obese
color_pal <- colorNumeric(
  palette = "RdYlBu",
  domain = joined_data$wtcircum_obese,reverse = TRUE
)

title_html <- tags$h3("Prevalence of Abdominal Obesity among women, across Indian States (NFHS-5)")

# Create the chloropleth map with the updated color scale
leaflet_map<-leaflet(joined_data) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(
    fillColor = ~color_pal(wtcircum_obese),
    weight = 1,
    color = "black",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 2,
      color = "white",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~paste0(
      name,
      ": ",
      format(wtcircum_obese, nsmall = 1),
      "%"
    ),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"
    )
  )%>%
  # Add a legend
  addLegend(
    position = "bottomright",
    pal = color_pal,
    values = ~wtcircum_obese,
    title = "Obesity Rate",
    opacity = 1
  ) %>%
  # Add a custom control for the map title
   addControl(
    html = title_html,
    position = "topright"
  )

leaflet_map

```


```{r}
saveWidget(leaflet_map, file = "chloropleth_map_fullsample.html")

```